import csv

# General Knowledge Questions to add
gk_questions = [
    ["What is the capital of France?", "The capital of France is Paris, located in the north-central part of the country along the Seine River."],
    ["Who discovered gravity?", "Sir Isaac Newton is credited with discovering the laws of gravity after observing an apple fall from a tree in 1666."],
    ["What is photosynthesis?", "Photosynthesis is the process by which plants convert sunlight, water, and carbon dioxide into oxygen and glucose for energy."],
    ["Who painted the Mona Lisa?", "Leonardo da Vinci painted the Mona Lisa, one of the most famous paintings in the world, created between 1503-1519."],
    ["What is the largest ocean?", "The Pacific Ocean is the largest ocean, covering more than 63 million square miles and containing more than half of the free water on Earth."],
    ["Who wrote Romeo and Juliet?", "William Shakespeare wrote Romeo and Juliet, one of his most famous tragic plays, around 1594-1596."],
    ["What is the speed of light?", "The speed of light in vacuum is approximately 299,792,458 meters per second or about 186,282 miles per second."],
    ["Who was the first person on the moon?", "Neil Armstrong was the first person to walk on the moon on July 20, 1969, during the Apollo 11 mission."],
    ["What is DNA?", "DNA (Deoxyribonucleic Acid) is a molecule that carries genetic instructions for the development and functioning of all living organisms."],
    ["Who invented the telephone?", "Alexander Graham Bell is credited with inventing the first practical telephone in 1876."],
    ["What is the largest planet?", "Jupiter is the largest planet in our solar system, with a mass more than twice that of all other planets combined."],
    ["What is democracy?", "Democracy is a system of government where citizens exercise power by voting to elect representatives or directly participating in decision-making."],
    ["Who was Albert Einstein?", "Albert Einstein was a theoretical physicist who developed the theory of relativity and won the Nobel Prize in Physics in 1921."],
    ["What causes seasons?", "Seasons are caused by Earth's tilted axis as it orbits the Sun, resulting in varying amounts of sunlight reaching different parts of Earth."],
    ["What is the Great Wall of China?", "The Great Wall of China is an ancient fortification system built to protect Chinese states from invasions, stretching over 13,000 miles."],
    ["Who discovered penicillin?", "Alexander Fleming discovered penicillin in 1928, the first widely used antibiotic that revolutionized medicine."],
    ["What is the smallest country?", "Vatican City is the smallest country in the world, with an area of only 0.17 square miles or 0.44 square kilometers."],
    ["Who was Mahatma Gandhi?", "Mahatma Gandhi was an Indian independence activist who led India to freedom from British rule through nonviolent civil disobedience."],
    ["What is the water cycle?", "The water cycle is the continuous movement of water through evaporation, condensation, precipitation, and collection on Earth."],
    ["Who invented the light bulb?", "Thomas Edison developed the first commercially practical incandescent light bulb in 1879."],
    ["What is the human body's largest organ?", "The skin is the largest organ of the human body, covering an average area of about 20 square feet."],
    ["What is the Eiffel Tower?", "The Eiffel Tower is an iconic iron lattice tower in Paris, France, built in 1889 and standing 1,083 feet tall."],
    ["Who wrote the Harry Potter series?", "J.K. Rowling wrote the Harry Potter series, consisting of seven fantasy novels published between 1997 and 2007."],
    ["What is evolution?", "Evolution is the process by which species change over time through natural selection and genetic variation."],
    ["What is the Sahara Desert?", "The Sahara is the world's largest hot desert, covering much of North Africa with an area of about 3.6 million square miles."],
    ["Who was Leonardo da Vinci?", "Leonardo da Vinci was an Italian Renaissance polymath known for his paintings, inventions, and scientific observations."],
    ["What is climate change?", "Climate change refers to long-term shifts in global temperatures and weather patterns, primarily caused by human activities."],
    ["What is the United Nations?", "The United Nations is an international organization founded in 1945 to promote peace, security, and cooperation among nations."],
    ["Who discovered America?", "Christopher Columbus is credited with discovering America in 1492, though indigenous peoples had lived there for millennia."],
    ["What is the periodic table?", "The periodic table is a tabular arrangement of chemical elements organized by atomic number and electron configuration."],
    ["What is Mount Everest?", "Mount Everest is Earth's highest mountain, standing at 29,032 feet (8,849 meters) above sea level in the Himalayas."],
    ["Who invented the airplane?", "The Wright Brothers, Orville and Wilbur Wright, invented and flew the first powered airplane in 1903."],
    ["What is the Big Bang Theory?", "The Big Bang Theory is the prevailing cosmological model explaining the origin of the universe from an extremely hot and dense state."],
    ["What is the Amazon Rainforest?", "The Amazon Rainforest is the world's largest tropical rainforest, covering much of northwestern Brazil and extending into neighboring countries."],
    ["Who was Marie Curie?", "Marie Curie was a physicist and chemist who conducted pioneering research on radioactivity and won Nobel Prizes in Physics and Chemistry."],
    ["What is the solar system?", "The solar system consists of the Sun and all objects bound to it by gravity, including eight planets and their moons."],
    ["What is the Olympic Games?", "The Olympic Games are international sporting events held every four years, featuring summer and winter sports competitions."],
    ["Who painted the Sistine Chapel?", "Michelangelo painted the Sistine Chapel ceiling between 1508 and 1512, creating one of the greatest masterpieces of Renaissance art."],
    ["What is a black hole?", "A black hole is a region in space where gravity is so strong that nothing, not even light, can escape from it."],
    ["What is the Taj Mahal?", "The Taj Mahal is an ivory-white marble mausoleum in Agra, India, built by Mughal emperor Shah Jahan in memory of his wife."],
    ["Who discovered electricity?", "While electricity was known in ancient times, Benjamin Franklin's experiments in the 1750s greatly advanced understanding of electrical phenomena."],
    ["What is the human brain?", "The human brain is the central organ of the nervous system, containing about 86 billion neurons and controlling all bodily functions."],
    ["What is World War II?", "World War II was a global conflict from 1939 to 1945 involving most nations, resulting in over 70 million casualties."],
    ["Who was Cleopatra?", "Cleopatra VII was the last active pharaoh of ancient Egypt, known for her intelligence, political acumen, and relationships with Roman leaders."],
    ["What is the Internet?", "The Internet is a global network of interconnected computers that communicate using standardized protocols to share information."],
    ["What is the Statue of Liberty?", "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor, gifted by France in 1886."],
    ["Who was Napoleon Bonaparte?", "Napoleon Bonaparte was a French military leader and emperor who dominated European affairs in the early 19th century."],
    ["What is global warming?", "Global warming is the long-term increase in Earth's average surface temperature due to increased greenhouse gas emissions."],
    ["What is the Colosseum?", "The Colosseum is an ancient Roman amphitheater in Rome, Italy, built in 70-80 AD and capable of seating 50,000 spectators."],
    ["Who wrote 1984?", "George Orwell wrote the dystopian novel 1984, published in 1949, depicting a totalitarian society under constant surveillance."],
    ["What is quantum mechanics?", "Quantum mechanics is a branch of physics that describes the behavior of matter and energy at the atomic and subatomic levels."],
    ["Who was Julius Caesar?", "Julius Caesar was a Roman general and statesman who played a critical role in the rise of the Roman Empire."],
    ["What is the Renaissance?", "The Renaissance was a period of cultural rebirth in Europe from the 14th to 17th century, marked by advances in art, literature, and science."],
    ["What is the Nile River?", "The Nile is the longest river in the world, flowing about 4,135 miles through northeastern Africa."],
    ["Who invented the printing press?", "Johannes Gutenberg invented the movable-type printing press around 1440, revolutionizing the spread of information."],
    ["What is a volcano?", "A volcano is an opening in Earth's crust through which molten rock, gases, and debris erupt onto the surface."],
    ["What is the Milky Way?", "The Milky Way is the galaxy containing our Solar System, consisting of billions of stars, planets, and cosmic dust."],
    ["Who was Martin Luther King Jr?", "Martin Luther King Jr. was an American civil rights leader who fought against racial discrimination through nonviolent resistance."],
    ["What is an ecosystem?", "An ecosystem is a community of living organisms interacting with each other and their physical environment."],
    ["What is the Industrial Revolution?", "The Industrial Revolution was a period of major industrialization from the late 18th to 19th century, transforming manufacturing and society."],
    ["Who discovered radioactivity?", "Henri Becquerel discovered radioactivity in 1896, though Marie Curie later coined the term and conducted extensive research."],
    ["What is the Pythagorean theorem?", "The Pythagorean theorem states that in a right triangle, the square of the hypotenuse equals the sum of squares of the other two sides."],
    ["What is the Louvre?", "The Louvre is the world's largest art museum in Paris, France, housing over 38,000 objects including the Mona Lisa."],
    ["Who was Aristotle?", "Aristotle was an ancient Greek philosopher and scientist whose works have influenced Western thought for over two millennia."],
    ["What is the Grand Canyon?", "The Grand Canyon is a steep-sided canyon in Arizona, USA, carved by the Colorado River over millions of years."],
    ["What is plate tectonics?", "Plate tectonics is the theory that Earth's outer shell is divided into plates that glide over the mantle, causing earthquakes and volcanism."],
    ["Who was William Shakespeare?", "William Shakespeare was an English playwright and poet, widely regarded as the greatest writer in the English language."],
    ["What is the Hubble Space Telescope?", "The Hubble Space Telescope is a space-based observatory launched in 1990, providing detailed images of distant galaxies and celestial objects."],
    ["What is an atom?", "An atom is the smallest unit of matter that retains the properties of an element, consisting of protons, neutrons, and electrons."],
    ["Who was Galileo?", "Galileo Galilei was an Italian astronomer and physicist who made pioneering observations supporting the Copernican heliocentric model."],
    ["What is the equator?", "The equator is an imaginary line around Earth's middle at 0° latitude, dividing the planet into Northern and Southern Hemispheres."],
    ["Who was Charles Darwin?", "Charles Darwin was a naturalist who developed the theory of evolution by natural selection, published in On the Origin of Species."],
    ["What is the Seven Wonders?", "The Seven Wonders of the Ancient World were remarkable constructions, including the Great Pyramid of Giza, the only one still standing."],
    ["What is the moon?", "The Moon is Earth's only natural satellite, orbiting at an average distance of 238,855 miles and affecting tides and Earth's rotation."],
    ["Who was Queen Elizabeth I?", "Queen Elizabeth I was Queen of England from 1558 to 1603, presiding over a golden age of English history and culture."],
    ["What is Buddhism?", "Buddhism is a religion and philosophy founded by Siddhartha Gautama (Buddha) focusing on enlightenment through meditation and ethical living."],
    ["Who invented the computer?", "Charles Babbage designed the first mechanical computer in the 1830s, while modern electronic computers evolved from work by multiple pioneers."],
    ["What is the French Revolution?", "The French Revolution was a period of radical social and political upheaval in France from 1789 to 1799, ending absolute monarchy."],
    ["What is gravity?", "Gravity is a fundamental force of nature that attracts objects with mass toward each other, keeping planets in orbit around stars."],
    ["Who was Confucius?", "Confucius was an ancient Chinese philosopher whose teachings emphasized morality, justice, and proper social relationships."],
    ["What is the Mediterranean Sea?", "The Mediterranean Sea is a sea connected to the Atlantic Ocean, surrounded by the Mediterranean Basin and almost completely enclosed by land."],
    ["What is the theory of relativity?", "Einstein's theory of relativity revolutionized physics by describing gravity as spacetime curvature and showing mass-energy equivalence."],
    ["Who was Abraham Lincoln?", "Abraham Lincoln was the 16th President of the United States who led the nation through the Civil War and abolished slavery."],
    ["What is the Parthenon?", "The Parthenon is an ancient Greek temple in Athens, built in the 5th century BC and dedicated to the goddess Athena."],
    ["Who was Mozart?", "Wolfgang Amadeus Mozart was an Austrian composer of the Classical period, considered one of the greatest musical geniuses in history."],
    ["What is the Great Barrier Reef?", "The Great Barrier Reef is the world's largest coral reef system off the coast of Australia, stretching over 1,400 miles."],
    ["Who was Plato?", "Plato was an ancient Greek philosopher, student of Socrates, and founder of the Academy in Athens."],
    ["What is the Panama Canal?", "The Panama Canal is an artificial waterway connecting the Atlantic and Pacific Oceans, completed in 1914 and revolutionizing maritime trade."],
    ["What is a gene?", "A gene is a unit of heredity made of DNA that determines specific characteristics passed from parents to offspring."],
    ["Who was Vincent van Gogh?", "Vincent van Gogh was a Dutch post-impressionist painter known for his bold colors and emotional honesty in works like Starry Night."],
    ["What is the Cold War?", "The Cold War was a period of geopolitical tension between the United States and Soviet Union from 1947 to 1991."],
    ["Who was Isaac Newton?", "Isaac Newton was an English mathematician and physicist who formulated the laws of motion and universal gravitation."],
    ["What is the Stonehenge?", "Stonehenge is a prehistoric monument in England consisting of a ring of standing stones, built around 3000 BC to 2000 BC."],
    ["Who was Helen Keller?", "Helen Keller was an American author and activist who overcame deafness and blindness to become a leading humanitarian."],
    ["What is the Magna Carta?", "The Magna Carta was a charter signed in 1215 limiting royal power and establishing the principle that everyone is subject to the law."],
    ["Who was Socrates?", "Socrates was an ancient Greek philosopher known for the Socratic method of questioning and his influence on Western philosophy."],
    ["What is the Fibonacci sequence?", "The Fibonacci sequence is a series where each number is the sum of the two preceding ones, often appearing in nature."],
    ["What is the Dead Sea?", "The Dead Sea is a salt lake bordering Jordan and Israel, the lowest point on Earth at 1,412 feet below sea level."],
    ["Who was Rosa Parks?", "Rosa Parks was an American civil rights activist whose refusal to give up her bus seat sparked the Montgomery Bus Boycott."],
    ["What is the Bill of Rights?", "The Bill of Rights is the first ten amendments to the U.S. Constitution, guaranteeing fundamental rights and liberties."],
    ["Who was Steve Jobs?", "Steve Jobs was the co-founder of Apple Inc. and a pioneer in personal computing, smartphones, and digital entertainment."],
    ["What is the Rosetta Stone?", "The Rosetta Stone is an ancient Egyptian artifact with inscriptions in three scripts, key to deciphering Egyptian hieroglyphics."],
    ["Who was Winston Churchill?", "Winston Churchill was the British Prime Minister during World War II, known for his leadership and inspiring speeches."],
    ["What is the Silk Road?", "The Silk Road was an ancient network of trade routes connecting China with the Mediterranean, facilitating cultural exchange."],
    ["Who was Nikola Tesla?", "Nikola Tesla was a Serbian-American inventor and engineer who made groundbreaking contributions to electrical engineering and wireless technology."],
    ["What is the Enlightenment?", "The Enlightenment was an 18th-century intellectual movement emphasizing reason, science, and individual rights over tradition."],
    ["Who was Anne Frank?", "Anne Frank was a Jewish girl whose diary documented her family's hiding during the Holocaust, becoming a symbol of resilience."],
    ["What is the Suez Canal?", "The Suez Canal is an artificial waterway in Egypt connecting the Mediterranean Sea to the Red Sea, opened in 1869."],
    ["Who was Harriet Tubman?", "Harriet Tubman was an American abolitionist who escaped slavery and led hundreds to freedom via the Underground Railroad."],
    ["What is the Acropolis?", "The Acropolis is an ancient citadel in Athens containing the remains of several historically significant buildings including the Parthenon."],
    ["Who was Nelson Mandela?", "Nelson Mandela was a South African anti-apartheid revolutionary who became the country's first black president from 1994 to 1999."],
    ["What is the Gutenberg Bible?", "The Gutenberg Bible was the first major book printed using movable type in 1455, marking a milestone in printing history."],
    ["Who was Beethoven?", "Ludwig van Beethoven was a German composer and pianist, one of the most influential figures in classical music history."],
    ["What is the Pantheon?", "The Pantheon is a former Roman temple in Rome, now a church, famous for its massive dome and influence on architecture."],
    ["Who was Amelia Earhart?", "Amelia Earhart was an American aviation pioneer and the first woman to fly solo across the Atlantic Ocean."],
    ["What is the Tropic of Cancer?", "The Tropic of Cancer is the circle of latitude at 23.5° north, marking the northernmost point where the sun appears directly overhead."],
    ["Who was Florence Nightingale?", "Florence Nightingale was a British nurse who founded modern nursing and improved sanitary conditions in hospitals."],
    ["What is the Leaning Tower of Pisa?", "The Leaning Tower of Pisa is a freestanding bell tower in Italy, famous for its unintended tilt caused by soft ground."],
    ["Who was Marco Polo?", "Marco Polo was a Venetian merchant and explorer who traveled extensively through Asia in the 13th century."],
    ["What is the Nazca Lines?", "The Nazca Lines are ancient geoglyphs in the Peruvian desert, depicting various animals and geometric shapes visible from the air."],
    ["Who was Joan of Arc?", "Joan of Arc was a French heroine who led armies during the Hundred Years' War, later canonized as a saint."],
    ["What is the Hoover Dam?", "The Hoover Dam is a concrete arch-gravity dam on the Colorado River, built during the Great Depression and generating hydroelectric power."],
    ["Who was Ernest Hemingway?", "Ernest Hemingway was an American novelist known for his economical writing style and works like The Old Man and the Sea."],
    ["What is the International Space Station?", "The International Space Station is a habitable artificial satellite in low Earth orbit, serving as a space research laboratory."],
    ["Who was Jane Austen?", "Jane Austen was an English novelist known for her romantic fiction, social commentary, and works like Pride and Prejudice."],
    ["What is the Terracotta Army?", "The Terracotta Army is a collection of terracotta sculptures depicting the armies of Qin Shi Huang, discovered in China in 1974."],
    ["Who was Sigmund Freud?", "Sigmund Freud was an Austrian neurologist who founded psychoanalysis, revolutionizing the understanding of the human mind."],
    ["What is Machu Picchu?", "Machu Picchu is a 15th-century Inca citadel in Peru, situated on a mountain ridge above the Sacred Valley."],
    ["Who was Albert Schweitzer?", "Albert Schweitzer was a German theologian, physician, and philosopher who received the Nobel Peace Prize for his humanitarian work."],
    ["What is the Golden Gate Bridge?", "The Golden Gate Bridge is a suspension bridge spanning the Golden Gate strait in San Francisco, completed in 1937."],
    ["Who was Pablo Picasso?", "Pablo Picasso was a Spanish painter and sculptor, co-founder of Cubism and one of the most influential artists of the 20th century."],
    ["What is an eclipse?", "An eclipse occurs when one celestial body passes into the shadow of another, such as a solar or lunar eclipse."],
    ["Who was Walt Disney?", "Walt Disney was an American animator and entrepreneur who created Mickey Mouse and founded The Walt Disney Company."],
    ["What is the Hanging Gardens of Babylon?", "The Hanging Gardens of Babylon were one of the Seven Wonders, terraced gardens allegedly built by King Nebuchadnezzar II."],
    ["Who was Benjamin Franklin?", "Benjamin Franklin was an American polymath, founding father, inventor, and diplomat who contributed to science and politics."],
    ["What is the Vatican?", "The Vatican is an independent city-state enclaved within Rome, serving as the spiritual and administrative center of the Catholic Church."],
    ["Who was Frida Kahlo?", "Frida Kahlo was a Mexican painter known for her surrealist self-portraits exploring identity, pain, and Mexican culture."],
    ["Who was Genghis Khan?", "Genghis Khan was the founder of the Mongol Empire, the largest contiguous land empire in history."],
    ["What is the Brooklyn Bridge?", "The Brooklyn Bridge is a hybrid cable-stayed suspension bridge in New York City, completed in 1883."],
    ["Who was Rembrandt?", "Rembrandt van Rijn was a Dutch painter known for his portraits, self-portraits, and use of light and shadow."],
    ["Who was Louis Pasteur?", "Louis Pasteur was a French biologist who discovered pasteurization, developed vaccines, and proved the germ theory of disease."],
    ["What is the Sydney Opera House?", "The Sydney Opera House is a multi-venue performing arts center in Australia, opened in 1973 with distinctive sail-like design."],
    ["Who was Alexander the Great?", "Alexander the Great was a Macedonian king who created one of the largest empires in ancient history through military conquest."],
    ["What is the Burj Khalifa?", "The Burj Khalifa is a skyscraper in Dubai, UAE, the tallest structure in the world at 2,722 feet."],
    ["What is the Alhambra?", "The Alhambra is a palace and fortress complex in Granada, Spain, known for Islamic architecture and intricate decorations."],
    ["Who was Emily Dickinson?", "Emily Dickinson was an American poet known for her unconventional style and prolific output of nearly 1,800 poems."],
    ["What is the CN Tower?", "The CN Tower is a communications and observation tower in Toronto, Canada, standing at 1,815 feet tall."],
    ["Who was Copernicus?", "Nicolaus Copernicus was a Renaissance astronomer who formulated the heliocentric model of the universe."],
    ["What is Angkor Wat?", "Angkor Wat is a temple complex in Cambodia, the largest religious monument in the world, originally built as a Hindu temple."],
    ["Who was Eleanor Roosevelt?", "Eleanor Roosevelt was an American political figure, diplomat, and activist who served as First Lady during FDR's presidency."],
    ["What is the Ring of Fire?", "The Ring of Fire is a major area in the Pacific Ocean basin where many earthquakes and volcanic eruptions occur."],
    ["Who was Michelangelo?", "Michelangelo was an Italian Renaissance artist known for his sculptures David and Pietà, and painting the Sistine Chapel ceiling."],
    ["What is the Forbidden City?", "The Forbidden City is a palace complex in Beijing, China, that served as the imperial palace for 24 emperors."],
    ["Who was Ramanujan?", "Srinivasa Ramanujan was an Indian mathematician who made extraordinary contributions to number theory despite little formal training."],
    ["What is Petra?", "Petra is an archaeological city in Jordan, famous for rock-cut architecture and water conduit system."],
    ["Who was Marie Antoinette?", "Marie Antoinette was the last Queen of France before the French Revolution, known for her lavish lifestyle."],
    ["What is Chichen Itza?", "Chichen Itza is a large pre-Columbian archaeological site in Mexico, built by the Maya civilization."],
]

# Append to existing CSV file
with open('data/faqs.csv', 'a', newline='', encoding='utf-8') as file:
    writer = csv.writer(file, quoting=csv.QUOTE_ALL)
    writer.writerows(gk_questions)

print(f"Successfully added {len(gk_questions)} general knowledge questions!")
print("Total questions in database:")

# Count total
import pandas as pd
df = pd.read_csv('data/faqs.csv')
print(f"{len(df)} FAQs")
