"""
Script to generate 1000+ FAQ entries for training the chatbot
"""
import csv

# Define 1000+ FAQ entries covering diverse topics
faqs = [
    # Technology & AI (50 questions)
    ["What is artificial intelligence?", "Artificial Intelligence (AI) is the simulation of human intelligence processes by machines to perform tasks that typically require human intelligence."],
    ["How does machine learning work?", "Machine learning uses algorithms and statistical models to enable computers to improve their performance on tasks through experience without being explicitly programmed."],
    ["What is deep learning?", "Deep learning is a subset of machine learning using neural networks with multiple layers to progressively extract higher-level features from data."],
    ["What is natural language processing?", "NLP is a branch of AI that helps computers understand and generate human language for applications like translation and chatbots."],
    ["What is computer vision?", "Computer vision is a field of AI that trains computers to interpret and understand visual information from the world like images and videos."],
    ["What is neural network?", "A neural network is a computing system inspired by biological neural networks designed to recognize patterns and learn from data."],
    ["What is reinforcement learning?", "Reinforcement learning is a machine learning approach where agents learn to make decisions by receiving rewards or penalties for their actions."],
    ["What is supervised learning?", "Supervised learning trains models on labeled data where the correct output is known allowing the model to learn the mapping between inputs and outputs."],
    ["What is unsupervised learning?", "Unsupervised learning finds patterns in data without labeled outputs using techniques like clustering and dimensionality reduction."],
    ["What is transfer learning?", "Transfer learning reuses a pre-trained model on a new problem allowing faster training and better performance with less data."],
    
    # Programming Languages (50 questions)
    ["What is Python?", "Python is a high-level interpreted programming language known for its simplicity and readability widely used in web development and data science."],
    ["What is JavaScript?", "JavaScript is a programming language that enables interactive web pages and is an essential part of web applications alongside HTML and CSS."],
    ["What is Java?", "Java is an object-oriented programming language designed to run on any platform through the Java Virtual Machine providing platform independence."],
    ["What is C++?", "C++ is a powerful general-purpose programming language that supports object-oriented programming and is used for system software and game development."],
    ["What is C#?", "C# is a modern object-oriented programming language developed by Microsoft for building Windows applications and games using .NET framework."],
    ["What is Ruby?", "Ruby is a dynamic interpreted programming language focused on simplicity and productivity with an elegant syntax that is natural to read."],
    ["What is PHP?", "PHP is a server-side scripting language designed for web development to create dynamic web pages and applications."],
    ["What is Swift?", "Swift is a powerful programming language developed by Apple for building iOS macOS and other Apple platform applications."],
    ["What is Kotlin?", "Kotlin is a modern programming language that runs on the JVM and is officially supported for Android app development by Google."],
    ["What is Go?", "Go is an open-source programming language developed by Google designed for building simple reliable and efficient software with built-in concurrency."],
    ["What is Rust?", "Rust is a systems programming language focused on safety and performance preventing memory errors and providing zero-cost abstractions."],
    ["What is TypeScript?", "TypeScript is a programming language that adds static typing to JavaScript helping developers catch errors early and write more maintainable code."],
    ["What is SQL?", "SQL (Structured Query Language) is a programming language used to manage and manipulate relational databases and retrieve data."],
    ["What is R programming?", "R is a programming language and environment for statistical computing and graphics widely used for data analysis and visualization."],
    ["What is MATLAB?", "MATLAB is a programming platform for engineers and scientists to analyze data develop algorithms and create models for technical computing."],
    ["What is Scala?", "Scala is a programming language that combines object-oriented and functional programming running on the JVM for scalable applications."],
    ["What is Perl?", "Perl is a high-level interpreted programming language known for text processing and system administration tasks with powerful regex support."],
    ["What is Dart?", "Dart is a programming language optimized for building user interfaces especially for Flutter framework to create cross-platform mobile apps."],
    ["What is Lua?", "Lua is a lightweight scripting language designed for embedded systems and game development known for its speed and small footprint."],
    ["What is Haskell?", "Haskell is a purely functional programming language emphasizing immutability and mathematical correctness for reliable software development."],
    
    # Web Development (60 questions)
    ["What is HTML?", "HTML (Hypertext Markup Language) is the standard markup language for creating web pages defining structure and content."],
    ["What is CSS?", "CSS (Cascading Style Sheets) is a stylesheet language used to describe the presentation and styling of HTML documents."],
    ["What is responsive design?", "Responsive design ensures websites adapt and display properly across different devices and screen sizes for optimal viewing experience."],
    ["What is frontend development?", "Frontend development creates the user interface and experience of websites using HTML CSS and JavaScript that users interact with directly."],
    ["What is backend development?", "Backend development handles server-side logic databases and application functionality that powers websites behind the scenes."],
    ["What is full-stack development?", "Full-stack development involves working on both frontend and backend aspects of web applications requiring knowledge of multiple technologies."],
    ["What is React?", "React is a JavaScript library for building user interfaces especially single-page applications through reusable components."],
    ["What is Angular?", "Angular is a TypeScript-based web application framework developed by Google for building dynamic single-page applications."],
    ["What is Vue.js?", "Vue.js is a progressive JavaScript framework for building user interfaces that is designed to be incrementally adoptable."],
    ["What is Node.js?", "Node.js is a JavaScript runtime built on Chrome's V8 engine that allows developers to run JavaScript on the server side."],
    ["What is Express.js?", "Express.js is a minimal web application framework for Node.js providing robust features for building web and mobile applications."],
    ["What is Django?", "Django is a high-level Python web framework that encourages rapid development and clean pragmatic design with built-in features."],
    ["What is Flask?", "Flask is a lightweight Python web framework that provides flexibility and simplicity for building web applications with minimal boilerplate."],
    ["What is Bootstrap?", "Bootstrap is a popular CSS framework that provides pre-built components and responsive grid system for rapid web development."],
    ["What is Tailwind CSS?", "Tailwind CSS is a utility-first CSS framework that provides low-level utility classes to build custom designs without writing CSS."],
    ["What is SASS?", "SASS is a CSS preprocessor that adds features like variables nesting and mixins making CSS more maintainable and powerful."],
    ["What is webpack?", "Webpack is a module bundler for JavaScript applications that bundles assets and dependencies for optimized deployment."],
    ["What is REST API?", "REST (Representational State Transfer) API is an architectural style for designing networked applications using HTTP requests to access resources."],
    ["What is GraphQL?", "GraphQL is a query language for APIs that enables clients to request exactly the data they need making APIs flexible and efficient."],
    ["What is JSON?", "JSON (JavaScript Object Notation) is a lightweight data interchange format that is easy for humans to read and machines to parse."],
    
    # Database (40 questions)
    ["What is a database?", "A database is an organized collection of structured information or data stored electronically in a computer system for easy access and management."],
    ["What is MySQL?", "MySQL is an open-source relational database management system using SQL for managing and organizing data in tables with relationships."],
    ["What is PostgreSQL?", "PostgreSQL is a powerful open-source relational database system known for extensibility and SQL compliance with advanced features."],
    ["What is MongoDB?", "MongoDB is a NoSQL document database that stores data in flexible JSON-like documents providing scalability and flexibility."],
    ["What is Redis?", "Redis is an in-memory data structure store used as database cache and message broker known for high performance and speed."],
    ["What is NoSQL?", "NoSQL databases store and retrieve data differently than relational databases providing flexibility for unstructured data and scalability."],
    ["What is ACID?", "ACID (Atomicity Consistency Isolation Durability) are properties that guarantee reliable database transactions even in case of failures."],
    ["What is database normalization?", "Database normalization organizes data to reduce redundancy and improve data integrity by dividing tables and defining relationships."],
    ["What is SQL injection?", "SQL injection inserts malicious SQL code into application queries exploiting vulnerabilities to access or manipulate database data."],
    ["What is database indexing?", "Database indexing creates data structures that improve the speed of data retrieval operations at the cost of additional storage and write time."],
    ["What is primary key?", "A primary key is a unique identifier for each record in a database table ensuring no duplicate entries and enabling quick lookups."],
    ["What is foreign key?", "A foreign key is a field in one table that refers to the primary key in another table establishing relationships between tables."],
    ["What is database sharding?", "Database sharding partitions data across multiple databases to distribute load and improve performance for large-scale applications."],
    ["What is database replication?", "Database replication copies data from one database to others ensuring data availability redundancy and improved read performance."],
    ["What is ORM?", "Object-Relational Mapping (ORM) translates between object-oriented programming and relational databases simplifying database operations."],
    ["What is database migration?", "Database migration changes database schema or moves data between systems while maintaining integrity and minimizing downtime."],
    ["What is stored procedure?", "A stored procedure is a prepared SQL code saved in database that can be reused improving performance and security."],
    ["What is database trigger?", "A database trigger automatically executes code in response to specific events on tables like inserts updates or deletes."],
    ["What is database view?", "A database view is a virtual table based on SQL query results providing simplified access to complex queries and enhancing security."],
    ["What is transaction?", "A database transaction is a sequence of operations performed as a single logical unit of work that either completes entirely or not at all."],
    
    # Cloud Computing (35 questions)
    ["What is cloud computing?", "Cloud computing delivers computing services including servers and storage over the internet allowing flexible resources and economies of scale."],
    ["What is AWS?", "Amazon Web Services (AWS) is a comprehensive cloud platform offering over 200 services including computing storage and databases."],
    ["What is Azure?", "Microsoft Azure is a cloud computing platform providing services for building testing deploying and managing applications through Microsoft datacenters."],
    ["What is Google Cloud?", "Google Cloud Platform (GCP) is a suite of cloud computing services running on the same infrastructure that Google uses internally."],
    ["What is SaaS?", "Software as a Service delivers applications over internet on subscription basis eliminating need for installation and maintenance."],
    ["What is PaaS?", "Platform as a Service provides platform allowing customers to develop run and manage applications without infrastructure complexity."],
    ["What is IaaS?", "Infrastructure as a Service offers virtualized computing resources over internet including servers storage and networking on-demand."],
    ["What is serverless?", "Serverless computing runs applications without managing servers with automatic scaling and pay-per-execution pricing model."],
    ["What is Lambda function?", "AWS Lambda is a serverless compute service that runs code in response to events automatically managing the computing resources."],
    ["What is EC2?", "Elastic Compute Cloud (EC2) provides scalable virtual servers in the cloud allowing users to run applications on demand."],
    ["What is S3?", "Amazon S3 (Simple Storage Service) is object storage service offering scalability data availability security and performance."],
    ["What is CDN?", "A Content Delivery Network (CDN) is a distributed network of servers that delivers web content to users based on their geographic location."],
    ["What is load balancer?", "A load balancer distributes network traffic across multiple servers to ensure no single server becomes overwhelmed improving reliability."],
    ["What is auto-scaling?", "Auto-scaling automatically adjusts computing resources based on demand ensuring optimal performance and cost efficiency."],
    ["What is VPC?", "Virtual Private Cloud (VPC) provides isolated section of cloud where users can launch resources in virtual network they define."],
    ["What is cloud migration?", "Cloud migration moves data applications and workloads from on-premises infrastructure to cloud environment for scalability and efficiency."],
    ["What is hybrid cloud?", "Hybrid cloud combines private and public clouds allowing data and applications to be shared between them for flexibility."],
    ["What is multi-cloud?", "Multi-cloud uses multiple cloud providers to avoid vendor lock-in and optimize services leveraging best offerings from each."],
    ["What is containerization?", "Containerization packages applications with their dependencies into containers for consistent deployment across different environments."],
    ["What is Docker?", "Docker is a platform that uses containerization to package applications with their dependencies for consistent deployment across environments."],
    
    # DevOps (45 questions)
    ["What is DevOps?", "DevOps combines software development and IT operations to shorten development cycles and provide continuous delivery with high quality."],
    ["What is CI/CD?", "Continuous Integration/Continuous Deployment automates building testing and deploying code changes to production rapidly and reliably."],
    ["What is Git?", "Git is a distributed version control system that tracks changes in source code during software development enabling collaboration."],
    ["What is GitHub?", "GitHub is a web-based platform for version control and collaboration allowing developers to store and manage Git repositories."],
    ["What is GitLab?", "GitLab is a DevOps platform providing Git repository management CI/CD pipelines and project management tools in one application."],
    ["What is Jenkins?", "Jenkins is an open-source automation server that enables continuous integration and continuous delivery of software projects."],
    ["What is Kubernetes?", "Kubernetes is an open-source container orchestration platform that automates deployment and management of containerized applications at scale."],
    ["What is microservices?", "Microservices is an architectural style that structures applications as collections of loosely coupled services that can be developed independently."],
    ["What is container orchestration?", "Container orchestration automates deployment scaling and management of containerized applications across clusters of machines."],
    ["What is infrastructure as code?", "Infrastructure as Code manages infrastructure using code and version control automating provisioning and ensuring consistency across environments."],
    ["What is Terraform?", "Terraform is an infrastructure as code tool that enables building changing and versioning infrastructure safely and efficiently."],
    ["What is Ansible?", "Ansible is an automation tool for configuration management application deployment and task automation using simple YAML syntax."],
    ["What is monitoring?", "Monitoring collects and analyzes system data to detect issues track performance and ensure services meet requirements continuously."],
    ["What is logging?", "Logging records events and messages from applications and systems for troubleshooting auditing and analysis purposes."],
    ["What is Prometheus?", "Prometheus is an open-source monitoring system with time-series database that collects metrics and provides alerting capabilities."],
    ["What is Grafana?", "Grafana is an open-source analytics and visualization platform that creates dashboards for monitoring data from various sources."],
    ["What is blue-green deployment?", "Blue-green deployment runs two identical environments switching traffic from old to new version reducing downtime and enabling rollback."],
    ["What is canary deployment?", "Canary deployment gradually rolls out changes to small subset of users before full deployment reducing risk of widespread issues."],
    ["What is feature flag?", "Feature flag toggles functionality on or off without deploying new code enabling controlled rollouts and A/B testing safely."],
    ["What is chaos engineering?", "Chaos engineering intentionally introduces failures into systems to test resilience and identify weaknesses before real incidents occur."],
    
    # Cybersecurity (50 questions)
    ["What is cybersecurity?", "Cybersecurity is the practice of protecting computer systems and networks from digital attacks and unauthorized access to maintain data confidentiality."],
    ["What is encryption?", "Encryption is the process of converting information into a code to prevent unauthorized access and ensure data security during transmission."],
    ["What is firewall?", "A firewall is a network security system that monitors and controls incoming and outgoing traffic based on predetermined security rules."],
    ["What is malware?", "Malware is malicious software designed to damage disrupt or gain unauthorized access to computer systems including viruses and trojans."],
    ["What is phishing?", "Phishing is fraudulent attempt to obtain sensitive information by disguising as trustworthy entity in electronic communication."],
    ["What is ransomware?", "Ransomware encrypts victim's files demanding payment for decryption key blocking access to data until ransom is paid."],
    ["What is DDoS attack?", "Distributed Denial of Service attack overwhelms target system with traffic from multiple sources making services unavailable to legitimate users."],
    ["What is VPN?", "Virtual Private Network creates secure encrypted connection over internet protecting privacy and enabling secure remote access to networks."],
    ["What is SSL/TLS?", "SSL/TLS protocols provide secure communication over networks using encryption to protect data transmitted between clients and servers."],
    ["What is two-factor authentication?", "2FA adds second layer of security requiring users to provide two different authentication factors to verify their identity."],
    ["What is penetration testing?", "Penetration testing simulates cyber attacks on systems to identify vulnerabilities and weaknesses before malicious actors exploit them."],
    ["What is zero trust security?", "Zero trust security model requires verification for every user and device attempting to access resources never trusting by default."],
    ["What is HTTPS?", "HTTPS is the secure version of HTTP using encryption to protect data exchanged between web browsers and websites from interception."],
    ["What is authentication?", "Authentication verifies the identity of users or systems ensuring they are who they claim to be before granting access."],
    ["What is authorization?", "Authorization determines what authenticated users are allowed to do controlling access to resources based on permissions."],
    ["What is brute force attack?", "Brute force attack tries all possible combinations systematically to crack passwords or encryption keys through exhaustive trial and error."],
    ["What is social engineering?", "Social engineering manipulates people into divulging confidential information or performing actions that compromise security."],
    ["What is virus?", "A computer virus is malicious code that replicates by inserting copies into other programs or files spreading infection to systems."],
    ["What is trojan?", "A trojan horse disguises malicious code as legitimate software tricking users into installing it to compromise system security."],
    ["What is spyware?", "Spyware secretly monitors user activity collecting information without consent often tracking browsing habits and personal data."],
    
    # Data Science (55 questions)
    ["What is data science?", "Data science combines statistics and computer science to extract insights and knowledge from structured and unstructured data."],
    ["What is data analytics?", "Data analytics systematically examines data using statistical methods to discover patterns trends and insights supporting informed decisions."],
    ["What is big data?", "Big data refers to extremely large datasets that can be analyzed computationally to reveal patterns and trends especially relating to human behavior."],
    ["What is data mining?", "Data mining discovers patterns and relationships in large datasets using statistical and machine learning techniques for insights."],
    ["What is data visualization?", "Data visualization presents data graphically using charts and graphs making complex information easier to understand and interpret."],
    ["What is pandas?", "Pandas is a Python library providing data structures and analysis tools for working with structured data efficiently."],
    ["What is NumPy?", "NumPy is a Python library for numerical computing providing support for large multi-dimensional arrays and mathematical functions."],
    ["What is scikit-learn?", "Scikit-learn is a Python library for machine learning providing simple efficient tools for data analysis and modeling."],
    ["What is TensorFlow?", "TensorFlow is an open-source machine learning framework developed by Google for building and training neural networks."],
    ["What is PyTorch?", "PyTorch is an open-source machine learning library developed by Facebook for building deep learning models with dynamic computation graphs."],
    ["What is Keras?", "Keras is a high-level neural networks API written in Python that runs on top of TensorFlow for easy deep learning model development."],
    ["What is Jupyter Notebook?", "Jupyter Notebook is an interactive computing environment for creating documents containing code visualizations and narrative text."],
    ["What is data cleaning?", "Data cleaning identifies and corrects errors inconsistencies and inaccuracies in datasets to improve data quality for analysis."],
    ["What is feature engineering?", "Feature engineering creates new features from existing data to improve machine learning model performance and predictive power."],
    ["What is cross-validation?", "Cross-validation evaluates machine learning models by splitting data into training and testing sets multiple times to assess generalization."],
    ["What is overfitting?", "Overfitting occurs when model learns training data too well including noise failing to generalize to new unseen data."],
    ["What is underfitting?", "Underfitting occurs when model is too simple to capture underlying patterns in data resulting in poor performance on both training and test data."],
    ["What is bias-variance tradeoff?", "Bias-variance tradeoff balances model simplicity and complexity to minimize total error and achieve optimal generalization performance."],
    ["What is gradient descent?", "Gradient descent is an optimization algorithm that iteratively adjusts parameters to minimize loss function by moving in direction of steepest descent."],
    ["What is confusion matrix?", "Confusion matrix displays performance of classification model showing true positives false positives true negatives and false negatives."],
    
    # Software Engineering (65 questions)
    ["What is software development?", "Software development is the process of conceiving designing and creating applications and frameworks to solve problems or meet specific needs."],
    ["What is agile methodology?", "Agile is an iterative approach to software development emphasizing flexibility and collaboration with continuous delivery of working software."],
    ["What is scrum?", "Scrum is agile framework using fixed-length iterations called sprints with defined roles and ceremonies for collaborative development."],
    ["What is waterfall methodology?", "Waterfall methodology follows sequential phases where each phase must be completed before next begins suitable for well-defined projects."],
    ["What is version control?", "Version control is a system that records changes to files over time allowing developers to recall specific versions and collaborate effectively."],
    ["What is code review?", "Code review is systematic examination of source code by peers to find bugs and improve code quality before integration."],
    ["What is refactoring?", "Refactoring is restructuring existing code without changing its external behavior to improve readability and reduce complexity."],
    ["What is technical debt?", "Technical debt refers to implied cost of additional work caused by choosing quick solutions instead of better approaches that take longer."],
    ["What is unit testing?", "Unit testing verifies individual components of software work correctly in isolation using automated tests for each function or method."],
    ["What is integration testing?", "Integration testing verifies that different modules or services work together correctly when combined in an integrated system."],
    ["What is test-driven development?", "Test-Driven Development (TDD) is a software development approach where tests are written before the actual code implementation."],
    ["What is debugging?", "Debugging is the process of finding and resolving defects or problems within computer programs that prevent correct operation."],
    ["What is API?", "An API (Application Programming Interface) is a set of protocols that allows different software applications to communicate with each other."],
    ["What is SDK?", "SDK (Software Development Kit) is a set of tools and libraries that developers use to create applications for specific platforms."],
    ["What is IDE?", "An IDE (Integrated Development Environment) is a software application providing comprehensive facilities for software development including editor and debugger."],
    ["What is compiler?", "A compiler translates source code written in high-level programming language into machine code or intermediate code for execution."],
    ["What is interpreter?", "An interpreter executes source code directly line by line without prior compilation translating and executing instructions simultaneously."],
    ["What is algorithm?", "An algorithm is a step-by-step procedure or formula for solving a problem or completing a task in a finite number of steps."],
    ["What is data structure?", "A data structure is a specialized format for organizing and storing data efficiently enabling effective access and modification."],
    ["What is object-oriented programming?", "OOP is a programming paradigm based on objects containing data and methods promoting code reusability and modularity through encapsulation."],
    ["What is functional programming?", "Functional programming treats computation as evaluation of mathematical functions avoiding changing state and mutable data."],
    ["What is design pattern?", "Design patterns are reusable solutions to common software design problems providing templates for solving recurring challenges."],
    ["What is singleton pattern?", "Singleton pattern ensures a class has only one instance and provides global access point to that instance."],
    ["What is factory pattern?", "Factory pattern creates objects without specifying exact class to be created providing interface for object creation."],
    ["What is MVC?", "Model-View-Controller is architectural pattern separating application into three interconnected components for organized code structure."],
    ["What is clean code?", "Clean code is code that is easy to read understand and maintain following consistent style and best practices."],
    ["What is code smell?", "Code smell indicates potential problems in code that may need refactoring though not necessarily bugs."],
    ["What is dependency injection?", "Dependency injection is design pattern where dependencies are provided to object rather than object creating them improving testability."],
    ["What is SOLID principles?", "SOLID is set of five design principles for object-oriented programming promoting maintainable and scalable software design."],
    ["What is DRY principle?", "Don't Repeat Yourself principle states that every piece of knowledge should have single unambiguous representation in system."],
    
    # Operating Systems (30 questions)
    ["What is operating system?", "An operating system is system software that manages computer hardware and software resources and provides services for computer programs."],
    ["What is Windows?", "Windows is a family of operating systems developed by Microsoft for personal computers and servers with graphical user interface."],
    ["What is Linux?", "Linux is an open-source Unix-like operating system kernel that forms basis of many distributions used for servers and embedded systems."],
    ["What is macOS?", "macOS is Apple's operating system for Macintosh computers known for user-friendly interface and integration with Apple ecosystem."],
    ["What is kernel?", "Kernel is core component of operating system managing system resources and providing interface between hardware and software."],
    ["What is process?", "A process is an instance of a program in execution with its own memory space and system resources managed by the operating system."],
    ["What is thread?", "A thread is the smallest sequence of programmed instructions that can be managed independently by a scheduler enabling multitasking."],
    ["What is virtual memory?", "Virtual memory extends physical memory by using disk space allowing systems to run larger applications than available RAM."],
    ["What is file system?", "File system organizes and stores files on storage devices providing methods for data retrieval and storage management."],
    ["What is shell?", "Shell is command-line interface that allows users to interact with operating system by typing commands for file and process management."],
    ["What is bash?", "Bash (Bourne Again Shell) is Unix shell and command language providing scripting capabilities for task automation on Linux systems."],
    ["What is PowerShell?", "PowerShell is task automation framework from Microsoft consisting of command-line shell and scripting language for Windows administration."],
    ["What is daemon?", "Daemon is background process that runs continuously performing system tasks without direct user interaction on Unix-like systems."],
    ["What is service?", "Service is program that runs in background providing functionality to other programs or users on Windows operating systems."],
    ["What is boot process?", "Boot process initializes operating system loading necessary software and drivers when computer is powered on."],
    ["What is BIOS?", "Basic Input/Output System is firmware that initializes hardware during boot process and provides runtime services for operating system."],
    ["What is UEFI?", "Unified Extensible Firmware Interface is modern replacement for BIOS providing enhanced boot features and security capabilities."],
    ["What is device driver?", "Device driver is software that enables operating system to communicate with hardware devices providing standardized interface."],
    ["What is system call?", "System call is programmatic way for programs to request services from operating system kernel accessing protected resources."],
    ["What is interrupt?", "Interrupt is signal to processor indicating event requiring immediate attention causing temporary suspension of current execution."],
    
    # Networking (40 questions)
    ["What is computer network?", "Computer network connects multiple devices enabling communication and resource sharing between computers using wired or wireless connections."],
    ["What is internet?", "The internet is a global network of interconnected computers that communicate using standardized protocols to share information and resources."],
    ["What is TCP/IP?", "TCP/IP is suite of communication protocols that define how data is transmitted over internet connecting different networks together."],
    ["What is IP address?", "IP address is unique numerical identifier assigned to each device on network enabling communication and data routing."],
    ["What is DNS?", "Domain Name System (DNS) translates human-readable domain names into IP addresses that computers use to identify each other on networks."],
    ["What is HTTP?", "HTTP (Hypertext Transfer Protocol) is the foundation of data communication on the World Wide Web enabling transfer of hypertext documents."],
    ["What is router?", "Router is networking device that forwards data packets between computer networks directing traffic on the internet."],
    ["What is switch?", "Network switch connects devices within local network forwarding data only to intended recipient improving network efficiency."],
    ["What is bandwidth?", "Bandwidth is maximum rate of data transfer across network path measured in bits per second indicating network capacity."],
    ["What is latency?", "Latency is time delay between sending and receiving data over network affecting responsiveness of applications and services."],
    ["What is protocol?", "Network protocol is set of rules governing communication between devices defining format timing and error handling for data exchange."],
    ["What is subnet?", "Subnet divides larger network into smaller logical networks improving performance security and management of network resources."],
    ["What is MAC address?", "MAC address is unique hardware identifier assigned to network interface card enabling device identification on local network."],
    ["What is port?", "Network port is virtual endpoint for communication identifying specific process or service on networked device using port numbers."],
    ["What is socket?", "Socket is endpoint for sending or receiving data across network combining IP address and port number for communication."],
    ["What is proxy server?", "Proxy server acts as intermediary between clients and servers forwarding requests and responses providing caching and security."],
    ["What is NAT?", "Network Address Translation translates private IP addresses to public IP addresses enabling multiple devices to share single public IP."],
    ["What is gateway?", "Gateway is network node that serves as access point to another network translating between different protocols or architectures."],
    ["What is packet?", "Packet is unit of data transmitted over network containing both data and routing information for delivery to destination."],
    ["What is network topology?", "Network topology describes arrangement and relationship of network devices defining how they are connected and communicate."],
    
    # Mobile Development (25 questions)
    ["What is mobile app development?", "Mobile app development is the process of creating software applications that run on mobile devices like smartphones and tablets."],
    ["What is Android development?", "Android development creates applications for Android operating system using Java or Kotlin programming languages and Android SDK."],
    ["What is iOS development?", "iOS development builds applications for Apple's iOS platform using Swift or Objective-C with Xcode development environment."],
    ["What is React Native?", "React Native is framework for building mobile applications using JavaScript and React enabling cross-platform development from single codebase."],
    ["What is Flutter?", "Flutter is Google's UI toolkit for building natively compiled applications for mobile web and desktop from single codebase using Dart."],
    ["What is Xamarin?", "Xamarin is Microsoft's platform for building cross-platform mobile applications using C# and .NET sharing code across platforms."],
    ["What is progressive web app?", "PWA is a web application that uses modern web capabilities to deliver app-like experience including offline functionality and push notifications."],
    ["What is native app?", "A native app is developed specifically for one platform using platform-specific languages and tools optimized for that environment."],
    ["What is hybrid app?", "A hybrid app combines web technologies with native code allowing single codebase to run on multiple platforms with native features."],
    ["What is app store?", "App store is digital distribution platform where users can browse download and purchase applications for their mobile devices."],
    ["What is Android SDK?", "Android Software Development Kit provides tools and libraries necessary for developing applications for Android platform."],
    ["What is Xcode?", "Xcode is Apple's integrated development environment for creating applications for iOS macOS watchOS and tvOS platforms."],
    ["What is mobile UI?", "Mobile UI is user interface design optimized for touch interaction on small screens with finger-friendly controls and gestures."],
    ["What is responsive mobile design?", "Responsive mobile design ensures applications adapt to different screen sizes and orientations providing optimal experience on all devices."],
    ["What is push notification?", "Push notification is message sent from server to mobile app appearing on device screen even when app is not actively running."],
    ["What is mobile backend?", "Mobile backend provides server-side functionality including databases APIs and cloud services supporting mobile applications."],
    ["What is app performance?", "App performance measures how quickly and efficiently mobile application responds to user interactions affecting user experience."],
    ["What is mobile analytics?", "Mobile analytics tracks user behavior within mobile applications providing insights into usage patterns and performance metrics."],
    ["What is app testing?", "App testing verifies mobile application functionality usability and performance across different devices and operating system versions."],
    ["What is mobile security?", "Mobile security protects applications and devices from threats ensuring data privacy and preventing unauthorized access."],
    
    # Blockchain & Crypto (20 questions)
    ["What is blockchain?", "Blockchain is a distributed ledger technology that records transactions across multiple computers in a way that makes them difficult to alter retroactively."],
    ["What is cryptocurrency?", "Cryptocurrency is digital or virtual currency using cryptography for security operating independently of central bank on blockchain technology."],
    ["What is Bitcoin?", "Bitcoin is first decentralized cryptocurrency created in 2009 enabling peer-to-peer transactions without intermediaries using blockchain."],
    ["What is Ethereum?", "Ethereum is blockchain platform enabling smart contracts and decentralized applications with its own cryptocurrency called Ether."],
    ["What is smart contract?", "Smart contract is self-executing contract with terms directly written in code automatically enforcing and executing agreements on blockchain."],
    ["What is mining?", "Mining is process of validating transactions and adding them to blockchain by solving complex mathematical problems receiving cryptocurrency rewards."],
    ["What is consensus mechanism?", "Consensus mechanism is protocol that blockchain networks use to achieve agreement on single data value among distributed processes."],
    ["What is proof of work?", "Proof of Work is consensus mechanism requiring computational work to validate transactions and create new blocks securing blockchain network."],
    ["What is proof of stake?", "Proof of Stake is consensus mechanism where validators are chosen based on cryptocurrency holdings rather than computational power."],
    ["What is decentralization?", "Decentralization distributes control and decision-making away from central authority spreading power across network participants."],
    ["What is NFT?", "Non-Fungible Token is unique digital asset representing ownership of specific item or content on blockchain proving authenticity and ownership."],
    ["What is DeFi?", "Decentralized Finance uses blockchain technology to recreate traditional financial systems without central intermediaries enabling peer-to-peer transactions."],
    ["What is wallet?", "Cryptocurrency wallet stores private keys enabling users to send receive and manage their digital assets on blockchain networks."],
    ["What is private key?", "Private key is secret cryptographic code allowing owner to access and control their cryptocurrency funds proving ownership."],
    ["What is public key?", "Public key is cryptographic code shared publicly that others use to send cryptocurrency functioning as account address."],
    ["What is gas fee?", "Gas fee is transaction cost paid to blockchain network validators for processing and validating transactions on platform like Ethereum."],
    ["What is token?", "Token is digital asset created on existing blockchain representing various assets or utility within specific ecosystem or application."],
    ["What is ICO?", "Initial Coin Offering is fundraising method where new cryptocurrency projects sell tokens to early investors to raise capital."],
    ["What is fork?", "Fork is change to blockchain protocol creating two separate paths one following old rules and one following new rules."],
    ["What is hash?", "Hash is fixed-size string of characters generated from input data used in blockchain to ensure data integrity and security."],
    
    # IoT & Embedded Systems (20 questions)
    ["What is Internet of Things?", "IoT refers to the network of physical devices embedded with sensors and software that connect and exchange data over the internet."],
    ["What is sensor?", "Sensor is device that detects and responds to physical input from environment converting it into electrical signals for processing."],
    ["What is actuator?", "Actuator is device that converts electrical signals into physical action controlling mechanisms and systems in IoT devices."],
    ["What is embedded system?", "Embedded system is dedicated computer system designed to perform specific functions within larger mechanical or electrical systems."],
    ["What is Arduino?", "Arduino is open-source electronics platform with easy-to-use hardware and software for building interactive projects and prototypes."],
    ["What is Raspberry Pi?", "Raspberry Pi is small affordable computer designed for education and hobbyist projects capable of running full operating system."],
    ["What is MQTT?", "MQTT is lightweight messaging protocol for small sensors and mobile devices optimized for IoT applications with minimal bandwidth."],
    ["What is edge computing?", "Edge computing processes data near source of generation reducing latency and bandwidth usage for faster real-time processing."],
    ["What is firmware?", "Firmware is software programmed into hardware devices providing low-level control for device's specific functions."],
    ["What is microcontroller?", "Microcontroller is small computer on single integrated circuit containing processor memory and programmable input/output peripherals."],
    ["What is GPIO?", "General Purpose Input/Output are programmable pins on microcontroller for interfacing with external devices and sensors."],
    ["What is PWM?", "Pulse Width Modulation varies power delivered to device by switching it on and off rapidly controlling brightness or motor speed."],
    ["What is serial communication?", "Serial communication transmits data one bit at a time over single communication channel used for device-to-device connection."],
    ["What is I2C?", "I2C is serial communication protocol enabling multiple devices to communicate over two wires using master-slave architecture."],
    ["What is SPI?", "Serial Peripheral Interface is synchronous serial communication protocol for short-distance communication between microcontrollers and peripherals."],
    ["What is smart home?", "Smart home uses IoT devices and automation to control lighting climate security and appliances remotely for convenience and efficiency."],
    ["What is wearable technology?", "Wearable technology includes electronic devices worn on body tracking health fitness and providing notifications and connectivity."],
    ["What is industrial IoT?", "Industrial IoT applies IoT technology to manufacturing and industry optimizing operations through connected sensors and analytics."],
    ["What is mesh network?", "Mesh network topology where each device connects to multiple others providing redundant paths and improving reliability."],
    ["What is zigbee?", "Zigbee is wireless communication protocol for low-power devices in IoT applications creating mesh networks for home automation."],
    
    # UI/UX Design (25 questions)
    ["What is UI design?", "UI (User Interface) design creates visual elements and layouts that users interact with making applications aesthetically pleasing and intuitive."],
    ["What is UX design?", "UX (User Experience) design focuses on enhancing user satisfaction by improving usability accessibility and pleasure of product interaction."],
    ["What is wireframe?", "A wireframe is visual guide representing skeletal framework of website or app showing layout and functionality without design details."],
    ["What is mockup?", "A mockup is static design representation showing visual appearance of product including colors fonts and images for stakeholder review."],
    ["What is prototype?", "A prototype is preliminary model of product used to test concepts and gather feedback before full-scale development."],
    ["What is user research?", "User research investigates target users and their requirements through observation interviews and analysis informing design decisions."],
    ["What is persona?", "Persona is fictional character representing typical user based on research helping designers understand user needs and behaviors."],
    ["What is user journey?", "User journey maps steps users take to accomplish goal with product identifying pain points and opportunities for improvement."],
    ["What is information architecture?", "Information architecture organizes and structures content in clear logical way making information easy to find and understand."],
    ["What is usability?", "Usability measures how effectively efficiently and satisfactorily users can achieve objectives when using product or system."],
    ["What is accessibility?", "Accessibility ensures products are usable by people with disabilities following standards and guidelines for inclusive design."],
    ["What is design system?", "Design system is collection of reusable components and standards guiding product design ensuring consistency across interfaces."],
    ["What is style guide?", "Style guide documents visual design standards including colors typography spacing and component usage ensuring brand consistency."],
    ["What is color theory?", "Color theory explains how colors interact and influence emotions guiding designers in creating effective color schemes for interfaces."],
    ["What is typography?", "Typography is art of arranging text in readable and visually appealing way using fonts sizes spacing and alignment."],
    ["What is white space?", "White space is empty area around design elements improving readability focus and visual hierarchy in interface layout."],
    ["What is visual hierarchy?", "Visual hierarchy arranges elements by importance using size color and position guiding users' attention through interface."],
    ["What is affordance?", "Affordance is quality of object suggesting how it should be used helping users understand possible interactions intuitively."],
    ["What is feedback?", "Feedback provides users with information about results of their actions confirming interactions and system status visually or audibly."],
    ["What is consistency?", "Consistency maintains uniform design patterns and behaviors throughout interface reducing learning curve and improving usability."],
    ["What is responsive design?", "Responsive design creates layouts that adapt seamlessly to different screen sizes and devices providing optimal viewing experience."],
    ["What is mobile-first design?", "Mobile-first design starts with mobile version then expands to larger screens ensuring good experience on smallest devices."],
    ["What is A/B testing?", "A/B testing compares two versions of design to determine which performs better based on user behavior and metrics."],
    ["What is card design?", "Card design organizes content into distinct containers making information scannable and easier to digest on digital interfaces."],
    ["What is hamburger menu?", "Hamburger menu is navigation icon with three horizontal lines that expands to reveal menu options saving screen space."],
    
    # Game Development (20 questions)
    ["What is game development?", "Game development is process of creating video games involving design programming art and audio to create interactive entertainment experiences."],
    ["What is game engine?", "Game engine is software framework providing tools and features for developing games including graphics physics and scripting capabilities."],
    ["What is Unity?", "Unity is popular cross-platform game engine for creating 2D and 3D games with visual editor and scripting in C#."],
    ["What is Unreal Engine?", "Unreal Engine is powerful game engine known for high-quality graphics used for creating AAA games and real-time 3D content."],
    ["What is game loop?", "Game loop is core structure of game continuously updating game state and rendering graphics typically running 60 times per second."],
    ["What is frame rate?", "Frame rate measures how many frames are rendered per second affecting smoothness and responsiveness of game visuals."],
    ["What is collision detection?", "Collision detection determines when game objects intersect or touch enabling realistic physics and gameplay interactions."],
    ["What is sprite?", "Sprite is 2D image or animation representing character object or background element in video games."],
    ["What is texture?", "Texture is image applied to 3D model surface adding visual detail and realism without increasing geometric complexity."],
    ["What is shader?", "Shader is program that determines how graphics are rendered controlling lighting colors and special effects on screen."],
    ["What is physics engine?", "Physics engine simulates realistic physical interactions including gravity collision and momentum in game worlds."],
    ["What is AI in games?", "Game AI creates intelligent behavior for non-player characters making them react realistically to player actions and environment."],
    ["What is level design?", "Level design creates game environments and challenges planning layout pacing and player progression through game world."],
    ["What is game asset?", "Game asset is any visual or audio element used in game including models textures sounds and animations."],
    ["What is rendering?", "Rendering is process of generating images from 3D models using lighting textures and effects creating final visual output."],
    ["What is multiplayer?", "Multiplayer enables multiple players to interact in same game simultaneously through local or online network connections."],
    ["What is game balancing?", "Game balancing adjusts difficulty rewards and mechanics to ensure fair challenging and enjoyable experience for all players."],
    ["What is game testing?", "Game testing identifies bugs glitches and design issues through systematic play ensuring quality before release."],
    ["What is monetization?", "Game monetization generates revenue through various methods including purchases subscriptions advertisements and in-game items."],
    ["What is esports?", "Esports is competitive video gaming at professional level with organized tournaments leagues and spectator following."],
    
    # Quality Assurance (25 questions)
    ["What is quality assurance?", "Quality assurance ensures software meets specified requirements through systematic monitoring and evaluation of development processes."],
    ["What is software testing?", "Software testing evaluates application functionality to identify defects and verify it meets requirements before release."],
    ["What is test case?", "Test case is set of conditions and steps to verify specific functionality producing expected results for validation."],
    ["What is test plan?", "Test plan documents testing strategy objectives scope resources and schedule providing roadmap for testing activities."],
    ["What is manual testing?", "Manual testing involves human testers executing test cases without automation tools to identify bugs and ensure quality."],
    ["What is automation testing?", "Automation testing uses specialized tools to execute tests automatically comparing actual outcomes with expected results efficiently."],
    ["What is regression testing?", "Regression testing ensures new code changes haven't adversely affected existing functionality by re-running previous test cases."],
    ["What is smoke testing?", "Smoke testing is preliminary testing to reveal simple failures severe enough to reject a prospective software release."],
    ["What is sanity testing?", "Sanity testing verifies specific functionality works correctly after minor changes before conducting more extensive testing."],
    ["What is performance testing?", "Performance testing evaluates how system performs under various conditions measuring speed scalability and stability under workload."],
    ["What is load testing?", "Load testing verifies system behavior under expected load conditions ensuring it can handle anticipated user traffic."],
    ["What is stress testing?", "Stress testing pushes system beyond normal capacity to identify breaking point and how it recovers from failure."],
    ["What is security testing?", "Security testing identifies vulnerabilities and weaknesses in software systems to protect against malicious attacks and data breaches."],
    ["What is usability testing?", "Usability testing observes real users interacting with product to identify usability issues and improve user experience."],
    ["What is acceptance testing?", "Acceptance testing validates software meets business requirements and is ready for deployment from stakeholder perspective."],
    ["What is alpha testing?", "Alpha testing is performed by internal team in controlled environment to identify bugs before releasing to external users."],
    ["What is beta testing?", "Beta testing releases software to limited external users to gather feedback and identify issues in real-world conditions."],
    ["What is white box testing?", "White box testing examines internal structures and workings of application with knowledge of source code and architecture."],
    ["What is black box testing?", "Black box testing examines functionality without knowledge of internal implementation focusing on inputs and expected outputs."],
    ["What is test automation framework?", "Test automation framework provides structure for organizing automated tests with reusable components and reporting capabilities."],
    ["What is continuous testing?", "Continuous testing automatically runs tests throughout development pipeline providing immediate feedback on code changes."],
    ["What is defect?", "Defect is flaw in software that causes it to behave unexpectedly or incorrectly requiring investigation and correction."],
    ["What is bug report?", "Bug report documents defect with steps to reproduce expected and actual results severity and environment information."],
    ["What is test coverage?", "Test coverage measures percentage of code tested by test cases indicating thoroughness of testing efforts."],
    ["What is exploratory testing?", "Exploratory testing simultaneously learns tests and designs tests using tester's creativity and experience without predefined scripts."],
    
    # Project Management (30 questions)
    ["What is project management?", "Project management applies knowledge skills and techniques to plan execute and complete projects successfully meeting objectives within constraints."],
    ["What is project scope?", "Project scope defines boundaries of project including deliverables requirements and work needed to complete project successfully."],
    ["What is milestone?", "Milestone is significant point or event in project schedule marking completion of major phase or deliverable."],
    ["What is stakeholder?", "Stakeholder is person or group with interest in project outcome who can affect or be affected by project decisions."],
    ["What is project charter?", "Project charter formally authorizes project defining objectives scope authority and high-level requirements providing direction."],
    ["What is risk management?", "Risk management identifies assesses and prioritizes risks developing strategies to minimize negative impacts on project."],
    ["What is resource allocation?", "Resource allocation assigns available resources to project tasks ensuring efficient utilization to meet deadlines and objectives."],
    ["What is critical path?", "Critical path is sequence of dependent tasks that determines minimum time needed to complete project affecting overall duration."],
    ["What is Gantt chart?", "Gantt chart visually displays project schedule showing tasks timelines dependencies and progress using horizontal bars."],
    ["What is sprint planning?", "Sprint planning meeting where team selects work from backlog and plans how to complete it during upcoming sprint."],
    ["What is daily standup?", "Daily standup is brief meeting where team members share progress obstacles and plans promoting transparency and collaboration."],
    ["What is retrospective?", "Retrospective is meeting where team reflects on sprint discussing what went well what didn't and how to improve processes."],
    ["What is product backlog?", "Product backlog is prioritized list of features and requirements waiting to be developed guiding team's work priorities."],
    ["What is sprint backlog?", "Sprint backlog contains tasks team commits to completing during sprint broken down from product backlog items."],
    ["What is burndown chart?", "Burndown chart tracks work remaining over time showing progress toward completing sprint or project goals visually."],
    ["What is velocity?", "Velocity measures amount of work team completes during sprint helping predict capacity for future sprints."],
    ["What is product owner?", "Product owner represents stakeholders defining product vision prioritizing backlog and making decisions about features."],
    ["What is scrum master?", "Scrum master facilitates scrum process removing obstacles and ensuring team follows agile practices effectively."],
    ["What is epic?", "Epic is large user story that can be broken down into smaller stories representing substantial features or initiatives."],
    ["What is user story?", "User story describes feature from end-user perspective explaining who wants what and why to guide development efforts."],
    ["What is acceptance criteria?", "Acceptance criteria define conditions that must be satisfied for user story to be considered complete and acceptable."],
    ["What is definition of done?", "Definition of done specifies criteria that work must meet to be considered complete ensuring quality and consistency."],
    ["What is technical debt?", "Technical debt refers to implied cost of additional work caused by choosing quick solutions instead of better approaches that take longer."],
    ["What is minimum viable product?", "MVP is version of product with just enough features to satisfy early customers and provide feedback for future development."],
    ["What is kanban board?", "Kanban board visualizes workflow using columns and cards to manage work in progress limiting tasks and improving flow efficiency."],
    ["What is work in progress limit?", "WIP limit restricts number of tasks in progress simultaneously preventing overload and maintaining steady workflow."],
    ["What is lead time?", "Lead time measures total time from request to delivery indicating how quickly team responds to and completes work."],
    ["What is cycle time?", "Cycle time measures time from starting work to completion indicating efficiency of development process."],
    ["What is blocker?", "Blocker is obstacle preventing team from completing work requiring immediate attention to maintain progress."],
    ["What is sprint review?", "Sprint review demonstrates completed work to stakeholders gathering feedback and discussing next steps for product development."],
]

# Write to CSV file with proper quoting
with open('data/faqs.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f, quoting=csv.QUOTE_ALL)
    writer.writerows(faqs)

print(f"✅ Successfully created {len(faqs) - 1} FAQ entries!")
print(f"Total questions: {len(faqs) - 1}")
print("File: data/faqs.csv")
